version: "3.8"
services:
  senko-bot:
    build:
      context: ./
      target: production
    restart: always

  senko-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: senko
      POSTGRES_PASSWORD: postgres
    